Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2022
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
escreval("digite um numero")
leia(numero)
se numero> 10 entao
escreval("o numero e maior que 10")
fimse

Fimalgoritmo