Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2022
Var
   custofabrica,custofinal:real
inicio
escreva("Informe o custo de fábrica do veículo: ")
leia(custoFabrica)
custoFinal <- (custoDeFabrica  1.45)  1.28
escreval("O custo para o consumidor final é de: ",custoFinal)


Fimalgoritmo